name: bulid 2 package

on:
  workflow_dispatch:
  push:
    tags:
      - v.**

jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - SNAPSHOT
        arch:
          - aarch64_cortex-a53

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-homeproxy
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.apk

      - name: Zip apk packages
        run: |
          zip -j ${{ matrix.arch }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*.apk
          echo -e "**Beta文件说明** 🎈:\n" >> release.txt
          echo -e "1. Subscription page slow response with a large number of nodes \n" >> release.txt
          echo -e "2. Refactor nft rules \n" >> release.txt
          echo -e "3. Support Clash selector, urltest etc \n" >> release.txt
          echo -e "4. Move ACL settings to a dedicated page \n" >> release.txt
          echo -e "5. Any other improvements \n" >> release.txt
          
      - name: Create Release zip
        uses: ncipollo/release-action@main
        with:
          token: ${{ secrets.TOKEN }}
          artifacts: "${{ matrix.arch }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.apk"
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: "release.txt"
          tag: v1.${{ github.run_number }}_${{ matrix.arch }}
